### ISSUE TITLE
Is this plugin dead ?

### ISSUE THREAD

**Issue by rumatoest** [Baratynskiy/kotlin-netbeans#122]
Hello.

There was a good start, but now I see that development on this plugin stopped.
Should I consider it as dead?

**Comment by yole** [comment]
We're no longer actively developing the plugin, and have no definite plans to resume work on it, but we're happy to accept community contributions to the code.

**Comment by Chris2011** [comment]
It's to bad to hear that. :(

**Comment by yole** [comment]
Unfortunately the usage numbers of the plugin were too low to justify further investment into its development.

**Comment by Chris2011** [comment]
I can understand it. Thx for the clarification.

**Comment by Chris2011** [comment]
Maybe you can label the open issues with bug and enhancements and maybe you can try to fix the critical bugs. Thx for the super work anyway :)

**Comment by rumatoest** [comment]
@yole 
> Unfortunately the usage numbers of the plugin were too low to justify further investment into its development.

First you should to make it work and then count active users.

Нет, ну реально вы не успели довести до ума плагин и уже что-то считаете. Он даже синтаксис нормально подсветить не может, я уже не говорю про автодополнение и прочие штуки. Какой нормальный разработчик будет этим пользоваться?

З.Ы. Кстати я более чем уверен, что качество Kotlin плагина в каком нибудь Atom, Sublime или VSCode будет намного лучше.

**Comment by Chris2011** [comment]
Please write in english that everyone can understand it. Thx.

**Comment by Polve** [comment]
I, for one, would have loved to use the plugin but the times I tried was so buggy and limited to be completely useless :-(

**Comment by geertjanw** [comment]
Usage numbers of the plugin may have been low because it was not nearly as useful as the equivalent features in IntelliJ IDEA.

**Comment by Chris2011** [comment]
https://news.ycombinator.com/item?id=16167187 I go with the first comment:

> I like Kotlin but I really wish they would draw a clearer line between kotlin the language (incl. compilers + generic tools) and the kotlin-plugin for IntelliJ IDEA. It seems they see the work on IDEA support for kotlin as an essential quality of new kotlin features. But guess what, there are people out there who don't want to use JetBrains' IDE, who prefer eclipse (for whatever reason) or who would be much happier to use an editor with LSP support.
If JetBrains didn't make most of their money with their IDE, they would probably put more effort in providing general tools that can be used with any IDE/editor. In this sense, I think JetBrains is hampering the success of kotlin. They should try to give kotlin a better organisational foundation.

I know that promoting your own IDE for best Kotlin support is good for you but not for the other users.

**Comment by Chris2011** [comment]
A stable plugin for NB or Eclipse with only a couple of features but is working and usable, is better than a half baked one.

**Comment by yole** [comment]
This issue is specifically about NetBeans, not about whatever other tools people may want to use for whatever reason. And as stated above, we did not (and still do not) see any evidence that the adoption of Kotlin is in any way hampered by its lack of support for NetBeans.

**Comment by Polve** [comment]
I understand that having to support a competitor ide is quite strange, but I, for one, am not using kotlin because I need to use netbeans in my projects.

Otherwise I would have already migrated a part of existing classes or written new ones in kotlin.

**Comment by yole** [comment]
Why do you _need_ to use netbeans in your projects? What exactly prevents you from using a different IDE?

**Comment by Polve** [comment]
I'm developing an application using the netbeans platform :-)

Anyway I can't force all my colleagues to change IDE and pay a fee that they now not need.

**Comment by yole** [comment]
OK, so Kotlin can't be used to develop applications for the NetBeans platform. We're fine with that.

"Paying a fee", on the other hand, is extremely subjective.

**Comment by rumatoest** [comment]
> Why do you need to use netbeans in your projects? What exactly prevents you from using a different IDE?

You will be surprised, but NetBeans have a good performance, maybe because of lack of some "advanced" features. 

From my experience NetBeans is much more faster than Eclipse and in my project it outperforms IntelliJ IDEA. I speak seriously, I'm trying to start using IDEA CE for about 1 year and I can not deal with huge lagging when I type code. So right now I have to  open IDEA to work with Kotlin code and switch back to NetBeans for other tasks.

In other projects with small amount of files/classes IDEA performs as fast as NetBeans ;)

> "Paying a fee", on the other hand, is extremely subjective.

Our boss can buy IDEA, but I should approve it and I see no reason in product which is not usable for our main project.

**Comment by moacirrf** [comment]
"My two cents"
Unfortunately the response is quite simple, Jetbrains dont have plans to improve this plugin for Netbeans, they dont have obligation to do it.

The community, is free to fork this.

**Comment by raderio** [comment]
> Kotlin can't be used to develop applications for the NetBeans platform

Why? Why can't? It is not compatible with Java?

**Comment by Polve** [comment]
Of course it is compatible, but since you need netbeans to develop for the platform and with netbeans you can't develop kotlin you should use two IDEs, and that's not quite good.

**Comment by Chris2011** [comment]
@yole what is your current, valuable statistic for this to messure it? What do you mean the usable value was to low? Where did you get these numbers? Only from the stars here at github? Make bug free alpha and put it into the plugin portal of NetBeans and you will see more downloads than here.

**Comment by geertjanw** [comment]
I suspect the Kotlin plugin for NetBeans was created to get NetBeans users interested in Kotlin and then, when real work with Kotlin needs to be done, effectively force them to switch to IntelliJ IDEA...

**Comment by yole** [comment]
The statistics we're using is the number of plugin update requests, which corresponds to the number of active users of the plugin.

The plugin was created because we had someone on our team interested in working on such a plugin. There is no nefarious plan here.

**Comment by joebowbeer** [comment]
On the one hand, it's good for Kotlin that JetBrains is behind it. However, it would also be good for Kotlin if it worked with multiple IDEs. The full downside of dangling a NetBeans plugin and then dropping it may not have been reached yet.

**Comment by geertjanw** [comment]
Usage numbers of the plugin may have been low because it was not nearly as useful as the equivalent features in IntelliJ IDEA. I made this point earlier in this thread and will happily make it again whenever 'statistics' are used to imply low NetBeans usage of the Kotlin plugin is a valid reason for not continuing to support it.

**Comment by yole** [comment]
If the main problem was low usefulness of the plugin, we'd still see many people trying the plugin and then abandoning it, which would be reflected in our statistics. We don't even see anyone try. We also see extremely few posts asking about NetBeans support in all the channels we monitor (our forums, Twitter, Slack, StackOverflow, Reddit, questions at conferences, and also this project on GitHub). (We do see plenty of people asking about Eclipse and VSCode, so it's not the case that we're blind to anything except for IntelliJ.)

If it turns out that lack of NetBeans support does become a significant barrier to adoption, we'll certainly hear about it from the community and will then resume work on the plugin.

**Comment by joebowbeer** [comment]
In my case, and I expect I'm not alone,  the accumulation of negative comments combined with the lack of any updates was the main deterrent. I don't install poorly rated plugins unless I see that some of the issues have been fixed.

**Comment by rumatoest** [comment]
> We don't even see anyone try.

Come on @yole, this is typical Microsoft thinking like "we are not selling windows phones for 3 years, but we are suspend platform development because of low market share"

This plug-in never worked. It is actually only suitable  for hello world projects, because it is even not able to highlight all syntax correctly.

**Comment by geertjanw** [comment]
Indeed, it's clear from this ongoing discussion that the "we don't even see anyone try" argument is a bit, well, thin...

**Comment by Chris2011** [comment]
@yole of course I tried, not that much, because at the moment I don't have to use kotlin but in the next months I will try it even more because we refactor our Java backend to kotlin + spring boot. I see my self have to switch to IntelliJ for Kotlin. Sooner or later. Unfortunately.

And of course the people using the plugin as you can see the tickets and the discussion. But I see it is not enough for you.

**Comment by kirill-zhukov** [comment]
I was going to try the plugin but didn't install it because of this thread and Github information that it is not supported. Also at netbeans page there were posts that it breaks existing projects. I guess I'm not the only who doesn't install the plugins without checking the reviews.
Regarding why NetBeans. Because it is much more liteweight than IntelliJ. I have both since we also do the Android development but it is really not as comfortable to use it as NetBeans. VSCode just doesn't support Java Development well, going through folders rather than packages and classes is not an option.
So my +1 vote for Kotlin support at netbeans especially as it is not done from scratch.
Please take into account that lots of people just read these posts and they do not give you any statistics and according to marketing rules there are most probably more of those who don't give you feedback.
Of course understood that JetBrains do not have obligations to support the plugin, however if statistics is the only matter I guess the real picture is a bit different.

**Comment by ratcashdev** [comment]
@yole I understand that JB is a commercial company. And it's fine. It's also beyond dispute that you're free to work on whatever amuses you or whatever has a positive impact on the bottom-line of JB. What is _not_ _that_ _much_ _ok_ is that (it seems) you're evaluating the success of an unfinished product (this plugin) mid-term.

Handing over such a code to the community is also less than ideal (but still better than not handing it over at all, obviously, and I still appreciate it). If I may suggest and politely ask, please either fix the current bugs, or cut them (whatever is not working properly should be disabled or removed) and publish a minimal product that does only a few things, but does it well. To me this comes down to  syntax highlighting, compilation, navigation, (unit)testing, debugging, and, ideally, usage search and (very basic) refactoring options (like field/method/class renames) in a pure kotlin-only project - and i realize this pretty much covers the currently advertised functionality. Anyway, with such a plugin ppl could actually start developing kotlin code without the headaches they currently encounter. Whoever wants more is free to pick IntelliJ.

Conversion of existing code, advanced refactorings, profiling, usage search in mixed kotlin-java projects could come later - even though I understand that may be an easier candy path to the world of Kotlin for small-er projects. Big-ger projects are either Java or Kotlin. Rarely both (within the same jar/war/...) for obvious reasons.

As for statistics: Once this plugin is stable enough, I bet @geertjanw could provide some numbers on the usage trends of Eclipse and Netbeans over the past years for JAVA and the proportion of devs using/trying kotlin support. That would be a much more objective comparison.

Also I would strongly encourage @geertjanw to seriously consider first-class support for Kotlin in NetBeans within ASF.

**Comment by geertjanw** [comment]
The beauty of the ASF is that we’re all equal and that I am not at all the one to seriously consider anything. :-) We all do it together, on the Apache NetBeans dev mailing list, like any other ASF project.

It is quite clear from this discussion though that the argument that there wasn’t enough interest to justify working on Kotlin support for NetBeans is, let’s say, a bit silly. You can’t provide a broken car and then say no one wants to drive it.

**Comment by ratcashdev** [comment]
I took the time to go through the existing open issues. It seems, a number of them could be closed with the latest release (0.2.0.1) even though internally it's still 0.2.0.0 and thus one has to first uninstall the plugin to have it upgraded.
Also using TestNg and/or `<kotlin.compiler.incremental>true</kotlin.compiler.incremental>` are actually causing some issues. But if I stick to the non-experimental compiler and JUnit, it's closer to usable (with some silly behavior sometimes). Irk that out together with https://github.com/JetBrains/kotlin-netbeans/issues/126 (or at least make RUN (F6) recompile the changed classes), and it would actually become usable.

**Comment by ratcashdev** [comment]
> It is quite clear from this discussion though that the argument that there wasn’t enough interest to justify working on Kotlin support for NetBeans is, let’s say, a bit silly. You can’t provide a broken car and then say no one wants to drive it.

Agree, but the actual supporting argument, the "why" (given by yole) should not be a main discussion topic here. And even if we somehow managed to convince or prove them wrong, it would have little purpose. They (JB) are free to say 'just because'.

The main topic should be the actual decision, the "what" (i.e. development discontinued) and how to move forward, because IMHO, kotlin support in Netbeans is important, and will get just more important over time.

**Comment by geertjanw** [comment]
Best to start/continue this discussion on Apache NetBeans dev mailing list, see netbeans.apache.org for details.

**Comment by 1Shaharear** [comment]
I am trying this http://plugins.netbeans.org/plugin/68590/kotlin
but I can't setup. if someone please send me video tutorial

**Comment by ratcashdev** [comment]
@kpretomazi remove it completely. Then download https://github.com/JetBrains/kotlin-netbeans/releases/tag/v0.2.0.1 and install.

**Comment by VisionsOfDrifting** [comment]
>It seems, a number of them could be closed with the latest release (0.2.0.1) even though internally it's still 0.2.0.0 and thus one has to first uninstall the plugin to have it upgraded.

@ratcashdev Do you know if anyone has forked the code and created a repository that is workable? I'm all for cutting bugs and making a minimal working version. I would much rather that than develop in NetBeans than any other IDE. In the meantime I will download and use v0.2.0.1 like you recommended.

Also, it is unfortunate this thread is mainly griefing yole instead of fixing the problem.

**Comment by ratcashdev** [comment]
BTW: if anyone would consider providing maintenance and bugfixing for this plugin, please see this comment: https://github.com/JetBrains/kotlin-netbeans/issues/126#issuecomment-387858450

**Comment by syslogic** [comment]
Apache NetBeans 9.0 has almost no plugins available ...how about a reboot?

**Comment by t-oster** [comment]
How about a Kickstarter or similar crowdfunding Project? I'd definitely support this plugin

**Comment by geertjanw** [comment]
Apache NetBeans 9.0 has hundreds of plugins. Just read this: https://blogs.apache.org/netbeans/entry/what-s-happened-to-my

**Comment by syslogic** [comment]
this is a religion. ever tried adding an 8.2 plugin? if they were so perfectly compatible, why they're not in the 9.0 repository?

**Comment by t-oster** [comment]
I was talking about kotlin support, which I really miss in NetBeans

**Comment by geertjanw** [comment]
Yes, if I was Jetbrains, I’d focus on creating strong Kotlin plugins for multiple tools, but it seems to me that Kotlin at least partly exists to promote IntelliJ IDEA. For NetBeans, I’d suggest you join the Apache NetBeans dev mailing list (see netbeans.apache.org) and propose/discuss Kotlin support for NetBeans there.

**Comment by Chris2011** [comment]
@syslogic what do you mean with a reboot? Reboot of this plugin? I soon (hopefully) we have LSP support in NetBeans, so it would be great to right a client for Kotlin to use LSP and enhance the missing stuff, separately.

> this is a religion. ever tried adding an 8.2 plugin? if they were so perfectly compatible, why they're not in the 9.0 repository?

Yes I often did this and I tried also 7.1 - 7.3, 8.0, 8.1 in my 8.2 instance (Verified and non verified) and yes they worked quite good. For NB 9.0 I have some compatibility problems for sure but that's ok, they will update sooner or later. If not, yes I think we should rethink that compatibility problem. I know some developers and I know it is a pain in the ass for them to update their plugin to be compatible. But this is an other discussion. Please join the Mailing list for this.

@t-oster if you would like to support this plugin, why not doing some work, like bug fixing, make it usable ;). That's even better. Fork it, do the work, make PR or make a new version.

**Comment by ratcashdev** [comment]
@Chris2011 

> if you would like to support this plugin, why not doing some work, like bug fixing, make it usable 

I tried. My investigation showed, that it would be very difficult (if not impossible) without strong support from IntelliJ, as the whole netbeans integration is dependent on a headless intelliJ embedded into NetBeans without sources. 
https://github.com/JetBrains/kotlin-netbeans/issues/126#issuecomment-387858450

**Comment by yole** [comment]
What do you mean by "without sources"? All components of the NetBeans plugin, including the IntelliJ core part, are fully open-source.

**Comment by ratcashdev** [comment]
@yole I could not find the sources needed to build new(er) versions of the jars inside lib/, i.e.

- idea-formatter.jar
- intellij-core.jar
- kotlin-converter.jar
- kotlin-formatter.jar
- kotlin-ide-common.jar
- openapi-formatter.jar

Apart from that, with the plugin loaded the project analysis of a bigger project (Glassfish) inside netbeans increased from a couple of seconds to 10 minutes and more. Most of the time was spent inside intellij-core, AFAICR.

**Comment by t-oster** [comment]
Here are some good News https://twitter.com/netbeans/status/1049976758278209537?s=20

**Comment by Chris2011** [comment]
Very great news of course. Only one thing, LSP can't handle syntax highlighting (yet) unfortunately. So here we can have a combination of parts of this plugin and using the LSP.

**Comment by dan-lugg** [comment]
https://github.com/JetBrains/kotlin-netbeans/issues/122#issuecomment-369674225

I was disappointed to see this being abandoned, but this remark IMO clearly justifies it. Hopefully there'll be an upswing in NetBeans users!

**Comment by devMls** [comment]
Here one more developer sad for that, i want to learn kotlin and netbeans is my default choise (java,, javascript and PHP). Eclipse is weird for me, Intel Jidea without javascript, don't fit me needs... I hope for a future with kotlin support in netbeans...

**Comment by Polve** [comment]
And here is another one: I'm planning to use kotlin since longtime but keep postponing because I can't use it easily in netbeans. And I don't want to change ide for the time being.

**Comment by mikehstrauss** [comment]
And another...

**Comment by jalgaba** [comment]
One more 🙏

**Comment by yole** [comment]
Sorry folks, this project is still dead and there are still no plans to resume any work on it.

**Comment by erokhins** [comment]
For the reference -- issue about donating to Apache NetBeans: https://github.com/JetBrains/kotlin-netbeans/issues/137
