### ISSUE TITLE
Cannot select main class

### ISSUE THREAD

**Issue by mglukhikh** [Baratynskiy/kotlin-netbeans#57]
Checked on https://github.com/Kotlin/kotlinx.html, module 'generate'. In Properties / Run / Main class, click Browse, you see no classes available.

**Comment by markiewb** [comment]
![2016-09-15_20h58_02](https://cloud.githubusercontent.com/assets/1857095/18563224/2180ff5a-7b87-11e6-80a5-dc4c1c7957e3.png)

**Comment by baratynskiy** [comment]
At the moment you can print the name of the main class by yourself in Properties/Run/Main class. In your case it is com.test.BlaKt.

**Comment by Mazuh** [comment]
Did you do it? My Netbeans still can't run my Kotlin ```hello-world```, even after I tried what @baratynskiy suggested.
