### ISSUE TITLE
Performance problem for https://github.com/Kotlin/ktor

### ISSUE THREAD

**Issue by mglukhikh** [Baratynskiy/kotlin-netbeans#58]
While opening the project, set a check for "Open Required Project". After it, NB opens the project and hangs for a very long time (and anyway, project scanning is unappropriate long).

**Comment by baratynskiy** [comment]
Maybe it happens because of O(n^2) in KotlinAnalyzer.analyzeFile() when indexing Kotlin files.

**Comment by mglukhikh** [comment]
Just to document: after analyzing memory dump we have decided to get rid of `Element`s in `NetBeansJava...` classes and use `ElementHandle`s instead. See http://wiki.netbeans.org/JavaHT_IDEIntegration.
