### ISSUE TITLE
Rename plugin

### ISSUE THREAD

**Issue by mglukhikh** [Baratynskiy/kotlin-netbeans#66]
"Kotlin plugin for NetBeans IDE" looks verbose a bit (and strange when we're inside NetBeans). I think something like just "Kotlin" / "Kotlin language" / "Kotlin plugin" / "Kotlin support" is better

**Comment by Chris2011** [comment]
How about "Kotlin4NetBeans" like Python4NetBeans or "Kotlin on NetBeans" like Perl on NetBeans?

**Comment by mglukhikh** [comment]
I mean here the name used inside the list of NetBeans plugins. There (e.g.) Python plugin is called just "Python" and C/C++ plugin is called just "C/C++"

**Comment by Chris2011** [comment]
Yeah there is Python and Python4NetBeans which is the name inside the Plugin manager and on the Plugin page. The name of the plugin represents the name in the Plugin manager and on the page.

**Comment by Chris2011** [comment]
But Kotlin could be fine too.
