### ISSUE TITLE
Strange problem on Linux (?)

### ISSUE THREAD

**Issue by mglukhikh** [Baratynskiy/kotlin-netbeans#78]
After installation of plugin, just create a project (Maven or Ant) and write "Hello world" sample. println is not resolved and nothing works. It's unclear how to make it working

**Comment by mglukhikh** [comment]
At least one PC exists when such an effect is occurred.

**Comment by cy6erGn0m** [comment]
Still doesn't work for me even after manual upgrade to NetBeans 8.2 with latest plugin

**Comment by mglukhikh** [comment]
Today I've successfully installed plugin on my old laptop by downloading from NetBeans plugin dialog. However, `println` is still not resolved. Looks like something is wrong.
